### ISSUE TITLE
Help for syntaxes

### ISSUE THREAD

**Issue by SkyCraft78** [tr7zw/Item-NBT-API#111]
Hello! 
I just saw your epic API for item's NBT. 
First of all, big thanks for making that, it helps me out very often! 
I wanna know if that's possible to set or add NBT to an item without managing tags;
For example, I directly wanna add `{Test:1b}` to the NBT. I know I can do it with NBT tag and compound, but is there a way to add it like that? 
Thanks and happy new year 🎉

**Comment by tr7zw** [comment]
That would be just .setBoolean(true). There are many wrappers for objects like NBTItem, NBTEntity, NBTTile, NBTChunk, NBTBlock, NBTGameprofile, NBTFile or NBTContainer, all sharing the same methods(of NBTCompound). Just wrap that object(perhabs gets the persistent data container for stuff that doesn't support tags normally), and then you can set data. You can also check the wiki here on GitHub for some examples.

**Comment by SkyCraft78** [comment]
Okay I understand, but there's no any way to add this :
```
{SkullOwner:{Id:"a62b13d0-d269-402a-91f3-897e6a40b907",Properties:{textures:[{Value:"eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMmMxYzE3OWFkNTE5NTVmMTUyMmM0OGVhOTkzMWYwOWMxNjI3NDFiNDVlMjJlOWQzZmViNjgyYzdlNWVkODI3NCJ9fX0="}]}}}
```
**Without** using every tag & compound system? Just like `nbti.addNBT("{SkullOwner:{Id:\"a62b13d0-d269-402a-91f3-897e6a40b907\",Properties:{textures:[{Value:\"eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMmMxYzE3OWFkNTE5NTVmMTUyMmM0OGVhOTkzMWYwOWMxNjI3NDFiNDVlMjJlOWQzZmViNjgyYzdlNWVkODI3NCJ9fX0=\"}]}}}")` ?

**Comment by SkyCraft78** [comment]
Okay, closed, Just found how to do like that :
```java
nbti.mergeCompound(new NBTContainer("{display:{Name:\"{\\\"text\\\":\\\"Portfolios\\\"}\"},SkullOwner:{Id:[I;-471448956,411780600,-2117854973,552810048],Properties:{textures:[{Value:\"" + base64 + "\"}]}}}"))
```
Thanks :)
