### ISSUE TITLE
NoSuchMethod

### ISSUE THREAD

**Issue by divios** [tr7zw/Item-NBT-API#112]
Hi! For some reason i keep getting this warning on console, is not game breaking but is quite annoying and i'm not sure why it is happening. https://hastebin.com/owulucipes.md

Also i link my pom, but i made sure to relocate the nbt api. https://hastebin.com/fipanazute.xml

**Comment by tr7zw** [comment]
Do you perhaps use some modified Server software that's not Spigot/Paper/Tuinity? Can you try running the 2.7.1 normal plugin jar, so it can run its self-check?

**Comment by divios** [comment]
Hi! Sorry for the late response, i'm using paper 1.16.4, this is the last log with nbt api jar, https://hastebin.com/ihuyonifog.yaml

**Comment by tr7zw** [comment]
Hmm the normal api is able to start and find everything, so why is it unable to find methods in your shaded version o_o? To be honest I'm not sure?!? Maybe try version 2.7.0(it's the same code-wise) so it has to download a new build.

**Comment by divios** [comment]
Yep i tried that and no luck either... but good news, i just tried on a linux vps ( i was doing the testing on my local machine which is windows) and it works without problems somehow

**Comment by tr7zw** [comment]
Going to guess that this is resolved since no other reports came in for 3 months.
