### ISSUE TITLE
Set a list.

### ISSUE THREAD

**Issue by NERDTimmie** [tr7zw/Item-NBT-API#121]
There is a method to get a Integer list but not a setter.

So how would is set a Integer list?

**Comment by tr7zw** [comment]
You don't need to set it. The list you get from the getter is linked to the compound and updates the internal values.

**Comment by NERDTimmie** [comment]
So you add a compound and then add extra entrys?
EG. i have 5 intergers i want to add. but no key for them who would i do that?
