### ISSUE TITLE
Fails to compile using maven 3.8 because repository is added using http

### ISSUE THREAD

**Issue by Derkades** [tr7zw/Item-NBT-API#129]
I couldn't find where but somewhere (probably in other dependencies of this project) it tries to download functional-annotations from a http maven repository. Maven 3.8 blocks these and only allows https repositories

```
Downloading from maven-default-http-blocker: http://0.0.0.0/de/tr7zw/functional-annotations/0.1-SNAPSHOT/maven-metadata.xml
[WARNING] Could not transfer metadata de.tr7zw:functional-annotations:0.1-SNAPSHOT/maven-metadata.xml from/to maven-default-http-blocker (http://0.0.0.0/): transfer failed for http://0.0.0.0/de/tr7zw/functional-annotations/0.1-SNAPSHOT/maven-metadata.xml
[WARNING] de.tr7zw:functional-annotations:0.1-SNAPSHOT/maven-metadata.xmlfailed to transfer from http://0.0.0.0/ during a previous attempt. This failure was cached in the local repository and resolution will not be reattempted until the update interval of maven-default-http-blocker has elapsed or updates are forced. Original error: Could not transfer metadata de.tr7zw:functional-annotations:0.1-SNAPSHOT/maven-metadata.xml from/to maven-default-http-blocker (http://0.0.0.0/): transfer failed for http://0.0.0.0/de/tr7zw/functional-annotations/0.1-SNAPSHOT/maven-metadata.xml
```

More information here: https://maven.apache.org/docs/3.8.1/release-notes.html

**Comment by tr7zw** [comment]
``Downloaded from codemc-repo: https://repo.codemc.org/repository/maven-public/de/tr7zw/functional-annotations/0.1-SNAPSHOT/maven-metadata.xml`` at least in the main build, it uses the codemc repo with https. ``http://0.0.0.0/`` looks like some malformed repo description in the pom? Build under 3.8.1 with the -U flag to redownload the dependencie worked as well.

**Comment by Derkades** [comment]
False alarm, the error message was caused by a different repository
