### ISSUE TITLE
Maven Repository

### ISSUE THREAD

**Issue by Trqhxrd** [tr7zw/Item-NBT-API#135]
You guys should add the URL of the Maven repository to the README.

I had to dig through old issues to find issues regarding the Maven repository so I could yoink the URL from the logs of the authors...

**Comment by tr7zw** [comment]
The maven url is in the wiki https://github.com/tr7zw/Item-NBT-API/wiki/Using-Maven and on the spigot page^^

**Comment by Trqhxrd** [comment]
Yeah I just saw it...
I'm stupid.

But you should add it to the README.

**Comment by tr7zw** [comment]
![grafik](https://user-images.githubusercontent.com/5133936/129777391-d65dd968-0f41-43e7-9584-bb5e52a1235e.png)
I mean it has it directly linked
