### ISSUE TITLE
Usage of commons-lang NotImplementedException

### ISSUE THREAD

**Issue by Derkades** [tr7zw/Item-NBT-API#138]
https://github.com/tr7zw/Item-NBT-API/blob/6b156c47e438ac7beec1a4a4ac878b8b613477a6/item-nbt-api/src/main/java/de/tr7zw/changeme/nbtapi/NBTCompoundList.java#L3

commons-lang was available in spigot previously but is no longer included, so this now results in a NoClassDefFoundError. Please switch to lang3 and declare it as a dependency:
```
<dependency>
    <groupId>org.apache.commons</groupId>
    <artifactId>commons-lang3</artifactId>
    <version>3.12.0</version>
</dependency>
```

**Comment by Derkades** [comment]
nevermind, this is my fault for not having a specific enough relocation policy when shading

**Comment by tr7zw** [comment]
I guess this still is a valid issue to be fixed in the next release, to not use a commons exception for that.
