### ISSUE TITLE
Error with others plugins

### ISSUE THREAD

**Issue by LaivyTLife** [tr7zw/Item-NBT-API#149]
Hey! i have issues here...

Issue: https://pastebin.com/JJ5KW57E
![image](https://user-images.githubusercontent.com/87931201/145696496-81a6447c-4520-4858-9924-ff665d79d0dc.png)

**Comment by LaivyTLife** [comment]
net.elicodes.vw.sdm.FakeIDataManager: https://pastebin.com/Bhi8Za6P

**Comment by tr7zw** [comment]
What does this have to do with the Nbtapi?
