### ISSUE TITLE
Heads become invisible if thrown onto the ground as an item. 

### ISSUE THREAD

**Issue by InfidelKilla** [tr7zw/Item-NBT-API#156]
If you throw a head or break a head, sometimes it won't show itself, and be invisible. It can still be picked up, it'll just be invisible. Now, player heads obtained from /skull didn't do this, but now with this API installed, that bug has seemed to have crept with it.

**Comment by tr7zw** [comment]
The api itself doesn't do anything. I guess the data on the head is in some form corrupted, but that had to be done by some other plugin, potentially using the nbtapi. Check your other plugins that might interact with items in that way.
