### ISSUE TITLE
1.18.2

### ISSUE THREAD

**Issue by ImFound** [tr7zw/Item-NBT-API#165]
please, add 1.18.2 support

**Comment by tr7zw** [comment]
2.9.2 https://ci.codemc.io/job/Tr7zw/job/Item-NBT-API/

**Comment by MorkaZ** [comment]
Is it possible to import 2.9.2 version with maven?
I was doing it by adding this dependency:
```
        <dependency>
            <groupId>de.tr7zw</groupId>
            <artifactId>item-nbt-api-plugin</artifactId>
            <version>2.8.0</version>
        </dependency>
```

**Comment by MorkaZ** [comment]
Thanks. Was not sure if 2.9.2 was already on maven :P

**Comment by tr7zw** [comment]
Worst case you can always check https://repo.codemc.io/#browse/browse:maven-public:de%2Ftr7zw%2Fitem-nbt-api-plugin .
