### ISSUE TITLE
Bunch of NBT API errors, breaks plugins

### ISSUE THREAD

**Issue by srnyx** [tr7zw/Item-NBT-API#169]
https://paste.srnyx.xyz/asepokajiq.properties

Notice how the first warnings are `[NBTAPI] [NBTAPI]`, and then the rest are `[CrazyEnchantments] [NBTAPI]`

These warnings also show up later, but I don't think they're too relevant:
```[19:03:50 WARN]: [NBTAPI] [NBTAPI] The NBT-API at 'package me.badbones69.crazyenchantments.nbtapi' seems to be outdated!
[19:03:50 WARN]: [NBTAPI] [NBTAPI] Current Version: '2.9.0-SNAPSHOT' Newest Version: 2.9.2'
[19:03:50 WARN]: [NBTAPI] [NBTAPI] Please update the nbt-api or the plugin that contains the api!```

**Comment by tr7zw** [comment]
Update to 2.9.2.

**Comment by srnyx** [comment]
> Update to 2.9.2.

```
[19:14:39 INFO]: NBTAPI version 2.9.2
[19:14:39 INFO]: Author: tr7zw
```

**Comment by tr7zw** [comment]
Then it's shaded into CrazyEnchantments, update CrazyEnchantments.

**Comment by srnyx** [comment]
> Then it's shaded into CrazyEnchantments, update CrazyEnchantments.

Ohhhh, alright, thank you!
