### ISSUE TITLE
NoSuchMethodException calling removeKey 1.13

### ISSUE THREAD

**Issue by kjburr** [tr7zw/Item-NBT-API#17]
When using the api upon calling nbtTileEntity.removeKey it's throwing NoSuchMethodException.

Here's a small stacktrace https://pastebin.com/pdxnhJH9

**Comment by tr7zw** [comment]
The Stacktrace points to TileEntity set nbt(Which gets called after removing a tag of a Tile). That reminds me that the reflection checks and tests I did do not include tiles/entities, so this missing is likely. Going to fix it and also update to 1.13.1.

**Comment by tr7zw** [comment]
Done :)
