### ISSUE TITLE
How to save as json array

### ISSUE THREAD

**Issue by aion1998** [tr7zw/Item-NBT-API#179]
# this is my way

## write

![image](https://user-images.githubusercontent.com/19725014/174499291-77fada9a-d998-4fc7-ab2e-efc12f3c5db3.png)

## read

![image](https://user-images.githubusercontent.com/19725014/174499354-0c64d3a1-f4a9-4858-ae39-f99529b9147c.png)

Why did the last conversion fail?

itemStack  is null

Under this common situation, what should I do the correct way?

> I don't know English, I rely on google translate

**Comment by tr7zw** [comment]
First of all, nbt is not valid json. So you can't use Gson to parse it.
NBT to nbt Strings: just use ``.toString()``. 
NBT from nbt String: ``new NBTContainer(nbtString)``
Also note that you don't want to toString NBTItem's. https://github.com/tr7zw/Item-NBT-API/wiki/Converting-Minecraft-Objects-to-NBT-and-Strings Has the full examples for that: ``NBTItem.convertItemtoNBT(item).toString()`` -> item as json String -> ``ItemStack rebuild = NBTItem.convertNBTtoItem(new NBTContainer(nbtString));``
