### ISSUE TITLE
Issues with 1.13 related builds.

### ISSUE THREAD

**Issue by Rusketh** [tr7zw/Item-NBT-API#19]
This bug report relates to pm's sent @tr7zw on spigot.

I am attempting to get my spigot plugins, that up till 1.13, worked with the nbt api.

The issue being that any attempt to call a 'de.tr7zw.itemnbtapi.NBTItem.hasKey(String)'. would relate in a null exception. 

I have installed and successfully ran a 1.12 build of my code using an older version of the nbt api (to be exact the one prior to 1.13 support). I have then tested the 1.7 and 1.8 snapshots of the nbt api. Each time I was greeted by the same errors I am getting on 1.13, at this point I am now certain this is no issue with my code. how ever the nbt api does claim to be compatible with my server in all instances.

I then decided to give up and try just removing my calls to 'de.tr7zw.itemnbtapi.NBTItem.hasKey(String)'. Yielding this error:
https://i.imgur.com/G86VvBL.png

Here is my code as it stands.
https://i.imgur.com/k5hSzbg.png

I already have null checks for my 'nbtItem' but I have also tried adding null checks on the property values. The error is persistent and It seems you can not write nbt data?

**Comment by tr7zw** [comment]
hasKey had the potential to return null instead of true/false. Fixed

**Comment by Rusketh** [comment]
Fixed thank you, closing this ticket.
