### ISSUE TITLE
convert nbt into itemstack

### ISSUE THREAD

**Issue by pawelkuwa** [tr7zw/Item-NBT-API#192]
hi i have problem, i cant find solution for my problem. i want to convert nbt tags from string exactly into itemstack ingame.
at first i must to create compound of nbt but i can't find how.
can you help me with this problem?

i want to translate string text with nbt into nbtcompound for get item from nbt compound.
thank you for attention.

**Comment by tr7zw** [comment]
https://github.com/tr7zw/Item-NBT-API/wiki/Converting-Minecraft-Objects-to-NBT-and-Strings

``ItemStack rebuild = NBTItem.convertNBTtoItem(new NBTContainer(string));``

**Comment by pawelkuwa** [comment]
```Caused by: java.lang.ClassNotFoundException: de.tr7zw.nbtapi.NBTCompound
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:151) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:103) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
        ... 23 more```
        
```            NBTContainer slot1Nbt = new NBTContainer(CreatePlayerFile.getShulkSlot(player, 1));
            slot1 = NBTItem.convertNBTtoItem(slot1Nbt);```

**Comment by tr7zw** [comment]
Class not found = you didn't put the plugin into the plugins folder.
