### ISSUE TITLE
Optimization

### ISSUE THREAD

**Issue by PunKeel** [tr7zw/Item-NBT-API#2]
Hello,

You should not create a NBTTagCompound when it's not required : https://github.com/tr7zw/Item-NBT-API/blob/master/src/main/java/de/tr7zw/itemnbtapi/NBTReflectionUtil.java#L272, for instance (and in `getXXX()` ;-))

**Comment by tr7zw** [comment]
I think you will get a nullpointer if you remove this line?

**Comment by PunKeel** [comment]
`if (nbttag == null) return false;` ;-)
