### ISSUE TITLE
Spelling Mistake in NBTReflectionUtil

### ISSUE THREAD

**Issue by ShaneBeee** [tr7zw/Item-NBT-API#206]
This is such a silly issue to open, but I keep seeing this.
https://github.com/tr7zw/Item-NBT-API/blob/79e1e62862349f92cd172cd878041fc2ab4a6298/item-nbt-api/src/main/java/de/tr7zw/changeme/nbtapi/NBTReflectionUtil.java#L297

"invalide" should be "invalid"

I would have opened a PR to fix this, but I didn't wanna be "that guy" opening a PR to fix a typo by one character 😆

**Comment by tr7zw** [comment]
Welp, guess I went full German mode and slapped an ``e`` at the end. Going to fix this next time I work on this repo.
