### ISSUE TITLE
Question: How to add CanPlaceOn multiple items.

### ISSUE THREAD

**Issue by BingYanchi** [tr7zw/Item-NBT-API#212]
/give @s minecraft:stone{CanPlaceOn: ["minecraft:grass_block", "minecraft:glass"]}

I don't see an example in the documentation and I don't know how to do it.

Can you tell me how to do the items in the above command?

**Comment by tr7zw** [comment]
(Haven't tested it, just going from the example you sent)
```java
List<String> canPlaceOn = nbti.getStringList("CanPlaceOn");
canPlaceOn.add("minecraft:grass_block");
canPlaceOn.add("minecraft:glass");
```
