### ISSUE TITLE
Get value of NBTCompound as Object

### ISSUE THREAD

**Issue by CollidaCube** [tr7zw/Item-NBT-API#217]
I don't care what type the value is, I just need the Object value of it. Is there a way I can do something like this?
```java
NBTCompound comp = ...;
Object value = comp.getValue("somekey");
```

**Comment by tr7zw** [comment]
I mean, the best it could return is the NBT-wrapped object, which wouldn't be of much help. You could make yourself a helper method that checks the type, and then grabs it.

**Comment by tr7zw** [comment]
Closing as stale.
