### ISSUE TITLE
Folia support

### ISSUE THREAD

**Issue by Q2297045667** [tr7zw/Item-NBT-API#225]
Are there any plans to support Folia in the future?
Folia is a great project, he solved many problems
https://github.com/PaperMC/Folia

**Comment by tr7zw** [comment]
I know about Folia, currently just don't have the time to check it. But I kinda assume shading the API should work, at least for item stacks. For Entities/BlockEntities it might run into some weird behavior, especially if you don't use Folias region scheduler system.

**Comment by Q2297045667** [comment]
> I know about Folia, currently just don't have the time to check it. But I kinda assume shading the API should work, at least for item stacks. For Entities/BlockEntities it might run into some weird behavior, especially if you don't use Folias region scheduler system.
Thank you for your reply. I'm glad you could consider Folia

**Comment by Q2297045667** [comment]
> I know about Folia, currently just don't have the time to check it. But I kinda assume shading the API should work, at least for item stacks. For Entities/BlockEntities it might run into some weird behavior, especially if you don't use Folias region scheduler system.

Thank you for your reply. I'm glad you could consider Folia

**Comment by tr7zw** [comment]
Since Mojmap is now working, this more or less added Folia support(just had to disable the block entity self-tests, since they try to load a chunk the normal way). This probably needs some more testing(I don't have any real Folia plugin setup), and the usual Folia restrictions apply(don't try to grab entity data over region group boundaries, probably crashes the server).

**Comment by Q2297045667** [comment]
> Since Mojmap is now working, this more or less added Folia support(just had to disable the block entity self-tests, since they try to load a chunk the normal way). This probably needs some more testing(I don't have any real Folia plugin setup), and the usual Folia restrictions apply(don't try to grab entity data over region group boundaries, probably crashes the server).

Thank you for your reply
