### ISSUE TITLE
nbtapi cant run on 1.18.2 mod server

### ISSUE THREAD

**Issue by GOOLDOVE** [tr7zw/Item-NBT-API#228]
I used a mohist 1.18.2 core (which supports the Forge/Bukkit/Spigot API), but I cannot use it well on the server
here is log 

[err_of_nbtapi.txt](https://github.com/tr7zw/Item-NBT-API/files/11662729/err_of_nbtapi.txt)

**Comment by tr7zw** [comment]
Correct, Forge/Fabric implementations are not supported.
