### ISSUE TITLE
1.20.3 compatibility

### ISSUE THREAD

**Issue by LoneDev6** [tr7zw/Item-NBT-API#260]
Hello!

1.20.3 introduces a change to the `NBTCompressedStreamTools#a(...)` method adding a new parameter.
You have to provide `NBTReadLimiter.a()` as second parameter to call this method.

Info:
https://mappings.cephx.dev/1.20.3/net/minecraft/nbt/NbtIo.html
https://mappings.cephx.dev/1.20.3/net/minecraft/nbt/NbtAccounter.html

My Mojang mapped code: 
```java
NbtIo.readCompressed(inputStream, NbtAccounter.unlimitedHeap());
```

**Comment by tr7zw** [comment]
Did you test with 2.12.2? That's already in the release.

**Comment by LoneDev6** [comment]
Nope I will do a test but the new signature of this method is still there on 1.20.4
https://mappings.cephx.dev/1.20.4/net/minecraft/nbt/NbtIo.html

Anyway I see you already added that signature compatibility, so it will surely work fine!
https://github.com/tr7zw/Item-NBT-API/blob/7bf91d0510eb421ac8821847bba4759154be4c04/item-nbt-api/src/main/java/de/tr7zw/changeme/nbtapi/utils/nmsmappings/ReflectionMethod.java#L243

**Comment by tr7zw** [comment]
I mean, all tests are passing in 1.20.4, including reading files/streams. So its all already implemented in the latest release :D
