### ISSUE TITLE
2.12.3 release is missing from Hangar

### ISSUE THREAD

**Issue by oddstr13** [tr7zw/Item-NBT-API#275]
While working on a plugin update utility for my server, I noticed that the 2.12.3 release is missing from the PaperMC Hangar https://hangar.papermc.io/tr7zw/NBTAPI/versions

**Comment by tr7zw** [comment]
With less than 100 downloads coming from Hangar, kinda forgot about it. Fixed.

**Comment by oddstr13** [comment]
No worries, I didn't even know about Hangar before yesterday myself. :)

Looked like they have a decent API, so setting up CI for auto-publishing should be doable. (same with Modrinth)

**Comment by tr7zw** [comment]
It's just this one plugin and also needs manual publishing on spigotmc, so it's fine. For my mods I do use mcpublish to do all of that automatically.
