### ISSUE TITLE
[Error] Error while calling the method 'asNMSCopy', loaded: true, Enum: ITEMSTACK_NMSCOPY, Passed Class: null

### ISSUE THREAD

**Issue by luapascoal** [tr7zw/Item-NBT-API#280]
Error: https://hastebin.com/share/osuqupomex.php
Code: https://hastebin.com/share/eludafeqiz.kotlin

Dispatch in async.

**Comment by tr7zw** [comment]
Solved on discord, was multithreaded modifying the same item.
