### ISSUE TITLE
Custom heads in 1.20.6

### ISSUE THREAD

**Issue by xeRicker** [tr7zw/Item-NBT-API#281]
I tried to make custom heads work with the 1.20.6 update but failed. I can confirm that the code in [this page](https://github.com/tr7zw/Item-NBT-API/wiki/Set-a-skull's-skin-using-NBT-API) is not working. 

https://pastebin.com/raw/Fqx0F5VW

![Zrzut ekranu 2024-06-13 132926](https://github.com/tr7zw/Item-NBT-API/assets/13571355/ac440c90-e561-4dd1-8130-272e7a6a5677)

**Comment by tr7zw** [comment]
Correct, this way isnt possible anymore, as vanilla tags are not stored as nbt at runtime.

**Comment by xeRicker** [comment]
I tried switching the tags around, but it didn't work either. Is there a workaround for that?

**Comment by tr7zw** [comment]
> vanilla tags are not stored as nbt at runtime

In 1.20.5+ NBT.modify on items is always just custom nbt, not vanilla nbt.

3 possible workarounds: 
- Convert the ItemStack to nbt, modify the component, turn the nbt back into an itemstack
- Build the itemstack nbt from the ground up and then turn it into an itemstack
- Build 1.20.4(or other earlier version) itemstack nbt, upgrade it, and then turn it into an itemstack.

**Comment by xeRicker** [comment]
Thanks for the response and the suggested workarounds. I'm still having trouble making custom heads work. Could you provide an example of the code using one of the listed methods?

**Comment by tr7zw** [comment]
I added a new method in 2.13.0 that simplifies the process. Take a look at ``NBT.modifyComponents``.

**Comment by xeRicker** [comment]
Thanks! It works like a charm :)

`public static ItemStack headFromTexture(String value) {
    ItemStack itemStack = new ItemStack(Material.PLAYER_HEAD);
    NBT.modifyComponents(itemStack, nbt -> {
        final ReadWriteNBT profileCompound = nbt.getOrCreateCompound("profile");
        profileCompound.setUUID("id", UUID.randomUUID());

        final ReadWriteNBT propertiesCompound = profileCompound.getCompoundList("properties").addCompound();
        propertiesCompound.setString("name", "textures");
        propertiesCompound.setString("value", value);
    });
    return itemStack;
}`

**Comment by tr7zw** [comment]
Nice, gonna check it and update the wiki(as I now also nuked the text from the spigotmc page, also linking the wiki instead).
