### ISSUE TITLE
Setting nbt clears item meta

### ISSUE THREAD

**Issue by Ekpoa** [tr7zw/Item-NBT-API#289]
After setting nbt it clears all current item meta, is there a way around this?

**Comment by Ekpoa** [comment]
nvm was using deprecated new NBTItem(item, true)

**Comment by tr7zw** [comment]
That isn't the issue(NBTItem is just deprecated so people move to NBT.modify/get instead). ItemMeta contains the nbt. So getting meta(contains a copy of the nbt), changing the nbt and then setting the meta reverts the nbt back to when the meta was created.
