### ISSUE TITLE
Error when compilling

### ISSUE THREAD

**Issue by Flashback083** [tr7zw/Item-NBT-API#29]
Hello ! I just start to use your api, but maybe i do something wrong, but i cannot compile it :/ 
When i try to compile i got this error : <br/>
>:compileJava FAILED
>FAILURE: Build failed with an exception.
>* What went wrong:
Could not resolve all files for configuration ':compileClasspath'.
> Could not resolve org.bstats:bstats-bukkit-lite:1.2.
  Required by:
      project : > com.github.tr7zw:Item-NBT-API:master-SNAPSHOT > com.github.tr7zw.Item-NBT-API:item-nbt-api-plugin:master-SNAPSHOT
   > Could not resolve org.bstats:bstats-bukkit-lite:1.2.
      > Could not get resource 'https://jitpack.io/org/bstats/bstats-bukkit-lite/1.2/bstats-bukkit-lite-1.2.pom'.
         > Could not GET 'https://jitpack.io/org/bstats/bstats-bukkit-lite/1.2/bstats-bukkit-lite-1.2.pom'. Received status code 401 from server: Unauthorized>
Do you have any idea why ? 

There is my dependencies : 
dependencies {
    compileOnly 'com.github.tr7zw:Item-NBT-API:master-SNAPSHOT'
}
And repositories : 
https://gist.github.com/Flashback083/f10a68d094ddad5da0c833323c62300e
Thanks for your help !
(On gradle)

**Comment by tr7zw** [comment]
Not exaclty sure what you are doing, but the error seems to be that it can't find the dependency "bstats" used by the plugin wrapper for the api. https://github.com/tr7zw/Item-NBT-API/blob/master/item-nbt-plugin/pom.xml#L54 Here is the maven repo location you can add.

**Comment by Flashback083** [comment]
okay that should be that, thanks !
