### ISSUE TITLE
Modify NBT of TileEntity on Folia

### ISSUE THREAD

**Issue by HarvelsX** [tr7zw/Item-NBT-API#294]
It apparently just doesn't work with yours because of this [patch](https://github.com/PaperMC/Folia/blob/d79708296e75ee4f26e78c2925f6e7d4217d0575/patches/server/0012-Block-reading-in-world-tile-entities-on-worldgen-thr.patch#L18) without any errors.
If there is no way around it, then throw an exception in that case.

**Comment by tr7zw** [comment]
I mean, it will probably throw a nullpointer exception? Also looking at the patch, you might need to be in the correct thread to be able to access the block. So the usual Folia restrictions apply.
