### ISSUE TITLE
Problem with Compound

### ISSUE THREAD

**Issue by Yoojexo** [tr7zw/Item-NBT-API#299]
A huge problem that prevents me from using Compound, which I really need. The point is that when I create a Compound via getOrCreateCompound() it is created and I can enter data into it and create another Compound in it, etc., but when I try to get the Compound from the item, it returns a null value, and the type is set to NBTTagEnd. In the screenshot below you can see that I output the contents of nbt with ItemStack as json, and below I tried to get data, and also checked the type of each tag.

![Modifying and reading data from an item](https://github.com/user-attachments/assets/7d2ac7cb-4b66-4755-ae84-8e1fd80fff18)

**Comment by tr7zw** [comment]
Without the code to the screenshot, I can't tell you much.
