### ISSUE TITLE
itemStackFromNBT does not include size of ItemStack (Paper 1.21.1)

### ISSUE THREAD

**Issue by Dartanboy** [tr7zw/Item-NBT-API#302]
As a very simple example:
```
public static String stringify(ItemStack item) {
    ReadWriteNBT nbt = NBT.itemStackToNBT(item);
    return nbt.toString();
}

public static ItemStack itemify(String itemStr) {
    ReadWriteNBT nbt = NBT.parseNBT(itemStr);
    return NBT.itemStackFromNBT(nbt);
}
```

Calling `stringify(new ItemStack(Material.BREAD, 16))` gives the correct string - `{Count:16b,id:"minecraft:bread"}` however calling `itemify({Count:16b,id:\"minecraft:bread\"})` results in a Bread ItemStack with only 1 item in it.

**Comment by tr7zw** [comment]
That string is not correct(at least for 1.20.5+). It needs to be "count", not "Count".

**Comment by Dartanboy** [comment]
I see, I just had some mistakes. I apologize!
