### ISSUE TITLE
NPE on 1.13

### ISSUE THREAD

**Issue by MiniDigger** [tr7zw/Item-NBT-API#31]
Running from be4dfa593b808f2f873563e650d846b533e3381a and latest paper

```
[21:58:05 INFO]: [NBTAPI] Found Spigot: v1_13_R2! Trying to find NMS support
[21:58:05 INFO]: [NBTAPI] NMS support 'MC1_13_R2' loaded!
```

![https://i.imgur.com/anSwcLk.png](https://i.imgur.com/anSwcLk.png)
![https://i.imgur.com/lBFljvp.png](https://i.imgur.com/lBFljvp.png)
![https://i.imgur.com/y8n7riN.png](https://i.imgur.com/y8n7riN.png)

seems like it has trouble getting the nbtcompound from my item
![https://i.imgur.com/2hwq2XC.png](https://i.imgur.com/2hwq2XC.png)
![https://i.imgur.com/P3oLnuc.png](https://i.imgur.com/P3oLnuc.png)

**Comment by tr7zw** [comment]
Has been fixed in version 2.0.
