### ISSUE TITLE
de.tr7zw.nbtinjector.NBTInjector.getNbtData returns null

### ISSUE THREAD

**Issue by kangarko** [tr7zw/Item-NBT-API#42]
Hey there,

I am working through an issue for a client where the method in the title seemingly returns null even if the entity has been patched, causing a NPE. No other errors were reported and the remaining class points to your plugin so I am posting it here in case you can help.

Here is the stack trace:
```
------------------------------------[ 09.07.2019 01:02:46 ]-----------------------------------
Boss 3.3.9 encountered a NullPointerException
Running CraftBukkit 1.8.8-R0.1-SNAPSHOT and Java 1.8.0_211
Plugins: WorldEdit v6.1.3;7a097ca, PlaceholderAPI v2.10.3, PermissionsEx v1.23.4, Boss v3.3.9, ViaVersion v2.1.1, NBTAPI v2.0.0-SNAPSHOT, Vault v1.7.2-b107, ProtocolLib v4.4.0, WorldGuard v6.2.1;84bc322, ASkyBlock v3.0.9.4, Essentials v2.16.1.214, DeluxeMenus v1.11.3, EssentialsChat v2.16.1.214, EssentialsGeoIP v2.16.1.214, EZPrestige v1.2.2, EssentialsSpawn v2.16.1.214, The Multiverse-Core Plugin
----------------------------------------------------------------------------------------------

More Information:
Failed to get NBT tag for SKELETON. Tag: KaBoss_KeepInside
NullPointerException (Unknown cause)
at org.mineacademy.boss.int. .COm6.native(SourceFile:185)
```

And here is the line 185:
![a](https://i.imgur.com/FLtrAs0.png)

As always, amazing library, thank you so much!

Matej

**Comment by tr7zw** [comment]
Does the NullPointer really have nothing attatched? That sounds kinda weird.

**Comment by kangarko** [comment]
Well we're checking if the given entity is not null on line 170, it is either null from getString or the getNbtData.

**Comment by tr7zw** [comment]
No I mean a full Stacktrace. With "you call a method and somewhere a NPE happens" I can't track down what happens 😅

**Comment by kangarko** [comment]
Thank you, I looked into it and it appeared to by on my side, closing for now :)
