### ISSUE TITLE
ClassNotFoundException using Spigot

### ISSUE THREAD

**Issue by CarrlosM** [tr7zw/Item-NBT-API#43]
The latest Spigot plugin version has **de.tr7zw.itemnbtapi.NBTItem**.

Using Jitpack for this repo, the path is **de.tr7zw.nbtapi.NBTItem** or **de.tr7zw.changeme.nbtapi** causing a ClassNotFoundException when code is being run.

**Comment by tr7zw** [comment]
The Jitpack repo is now unsupported, use the repo linked on the plugin page.
