### ISSUE TITLE
Update Javassist version

### ISSUE THREAD

**Issue by ZiluckMichael** [tr7zw/Item-NBT-API#44]
javassist is not on version 3.26.0. The old version has a dead javadoc reference. If a build requires successful javadoc generation, your outdated dependency causes everything else to fail. Please update this ASAP

**Comment by tr7zw** [comment]
https://mvnrepository.com/artifact/org.javassist/javassist
3.25.0-GA is the newest version, and the javadoc is up too (https://repo1.maven.org/maven2/org/javassist/javassist/3.25.0-GA/javassist-3.25.0-GA-javadoc.jar).
Not sure if I can help you with that, version "3.26.0-GA" is in their repo's pom, but currently in development/not released yet.
