### ISSUE TITLE
Can't work with 1.7.10!

### ISSUE THREAD

**Issue by thtTNT** [tr7zw/Item-NBT-API#5]
Sorry for my poor English. I use the spigot 1.7.10. But it tells that can't find the class com/google/gson/JsonSyntaxException. It must be higher version to execute this plugin?

**Comment by tr7zw** [comment]
Yea I encountered the same problem. 1.7.10 is missing some methods and is terribly outdated. I may fix this in the future, but right now 1.7 isn't supported.

**Comment by electro2560** [comment]
Sorry to comment on a closed issue. To fix this you need to include gson library within the plugin. Gson wasn't added to the server jar until version 1.8.3.

**Comment by tr7zw** [comment]
Yea. I will take a look at it, on rather just disabling the 2 methods that use gson for 1.7, or putting gson into the plugin. Kinda annoying to have patch around this much to get it working on a 3-year-old mc version^^.
