### ISSUE TITLE
[QUESTION] Can Item-NBT-API store custom NBT data in items between server restarts?

### ISSUE THREAD

**Issue by PublicGameCoder** [tr7zw/Item-NBT-API#73]
Can Item-NBT-API be used to store custom NBT data within items between server restarts?

**Comment by tr7zw** [comment]
That is the main and original purpose of this lib. You can store whatever data on items, and it doesn't matter where they get stored or what really happens to them, restarts included.

**Comment by PublicGameCoder** [comment]
Alright thank you. Then my code just didn't seem to work.
Since I couldn't retrieve any custom data instead of already existing properties on the item's nbt.
Thanks for clarification.
