### ISSUE TITLE
Adding a config to the standalone Plugin

### ISSUE THREAD

**Issue by tr7zw** [tr7zw/Item-NBT-API#79]
I need to check what should/can be added to the config, for now it should be:

- Check for updates
- bStats
- NBT-Injector

**Comment by SlimeDog** [comment]
Please, add configuration file supports disabling update checks. We have our own automagical update checker, and we block unnecessary outbound network traffic by plugins (at the firewall).

**Comment by tr7zw** [comment]
You can currently use an API call to disable the update check(and bStats for that matter if it get's blocked anyway), but since they only run once during onEnable it should™️ be fine for now. But yes, config file to do it without a plugin is still planned.
