### ISSUE TITLE
maven?

### ISSUE THREAD

**Issue by AmiT177** [tr7zw/Item-NBT-API#8]
Hey,
is there a maven repo for this lib?

Thanks,
Amit

**Comment by akashaggarwal7** [comment]
@AmiT177 Clone the git using `git clone`, inside the cloned directory run `maven install`. I don't think there is a public maven repo for this yet.

**Comment by AmiT177** [comment]
Already did, thanks anyway :D

**Comment by egg82** [comment]
Wanted to pop in and say that I have a public Maven repo of this project going here:
https://www.myget.org/feed/egg82-java/package/maven/de.tr7zw/Item-NBT-API

```
<repository>
  <id>egg82-ninja</id>
  <url>https://www.myget.org/F/egg82-java/maven/</url>
</repository>
...
<dependency>
  <groupId>de.tr7zw</groupId>
  <artifactId>Item-NBT-API</artifactId>
  <version>1.5.1</version>
  <scope>provided</scope>
</dependency>
```

Though if @tr7zw wanted to make a repo themselves it's free and (fairly) easy on the site I linked.
