### ISSUE TITLE
1.16.1 missing methods

### ISSUE THREAD

**Issue by LoneDev6** [tr7zw/Item-NBT-API#84]
Hello!
I just drop this log here in order to keep track of the update, I will remap the missing variables/methods:

[11:41:20] [Server thread/INFO]: [NBTAPI] Unable to find the method 'e' in 'NBTTagCompound' Enum: COMPOUND_GET_TYPE
[11:41:20] [Server thread/INFO]: [NBTAPI] Unable to find the method 'create' in 'TileEntity' Enum: TILEENTITY_LOAD
[11:41:20] [Server thread/INFO]: [NBTAPI] Unable to find the method 'load' in 'TileEntity' Enum: TILEENTITY_SET_NBT
[11:41:20] [Server thread/INFO]: [NBTAPI] Unable to find the method 'f' in 'Entity' Enum: NMS_ENTITY_SET_NBT

**Comment by tr7zw** [comment]
I'll publish the 1.16.1 update later today :)

**Comment by LoneDev6** [comment]
COMPOUND_GET_TYPE is now "d"
TILEENTITY_LOAD has added a new parameter in the function "create", this needs to be handled

**Comment by LoneDev6** [comment]
> 
> 
> I'll publish the 1.16.1 update later today :)

ooooh, did you finish it? I'll stop working on it if you already fixed all the stuff :D

**Comment by tr7zw** [comment]
I'm at work rn, but only 4 broken mappings sounds like it should be updateable rather quickly. So I could start to update it in about 5 hours, feel free to make a pr before that.

**Comment by LoneDev6** [comment]
Thanks! :D
Just tell me how to handle this:
TILEENTITY_LOAD method got a new parameter, do I have to make a new enum called TILEENTITY_LOAD_1_16 with the new signature?

**Comment by tr7zw** [comment]
Yea mark the old enum that it only is avaliable till 1.15, create a new one that is marked 1.16+ and at the place where it's used a simple version check should do it. (Also remember to add the 1.16 to the self check in pom)

**Comment by LoneDev6** [comment]
idk what you mean about the pom so i'll leave it to you :D lol
https://github.com/tr7zw/Item-NBT-API/pull/85

**Comment by tr7zw** [comment]
Fixed some stuff but still failing because of imports? Can't really check that without having it in the ide^^.

**Comment by LoneDev6** [comment]
> 
> 
> Fixed some stuff but still failing because of imports? Can't really check that without having it in the ide^^.

Probably, I will fix them now ;)

**Comment by LoneDev6** [comment]
Should be ok now

**Comment by tr7zw** [comment]
https://github.com/tr7zw/Item-NBT-API/runs/807027504?check_suite_focus=true#step:4:13173 Tile Entities in 1.16.1 used the wrong method/wrong number of args.

**Comment by tr7zw** [comment]
But yea looks like when that is fixed it should be done (at least no other tests seem to fail).
