### ISSUE TITLE
NBT upgrading and compatibility

### ISSUE THREAD

**Issue by Favorlock** [tr7zw/Item-NBT-API#97]
Is it possible to upgrade serialized NBT? One of the plugins I have been working on deals with blockchain technology and we use NBTAPI to save the exact state of the item when configuring their tokens, however, I've noticed that updating the server version can lead to breakage. Do you have any suggestions for how best to handle this?

**Comment by tr7zw** [comment]
I'll have to look deeper into how the DataFixers work, in order to upgrade Item/Entity/Tile NBT. It could be that ItemStacks correctly update when you recreate them from a NBTContainer(But I actually never really tested what happens when you throw 1.8 NBT into 1.16 for example, but is worth looking into).

**Comment by Favorlock** [comment]
Thanks! It seems like it can be pretty easy for the NBT to run into issues updating as I believe I had upgraded from 1.13 to 1.15 and still encountered errors upon deserialization.

**Comment by tr7zw** [comment]
Was there anything noteworthy? This is still a big untested/undocumented area, so any findings would be nice.

**Comment by Favorlock** [comment]
The only thing I found is more of a backwards-compatibility issue, which I can't reasonably expect to have a workaround implemented since Spigot doesn't support backwards-compatibility.

**Comment by tr7zw** [comment]
Yea Minecraft, in general, doesn't have a good concept of going backwards. Might be an interesting project to create a "whatever version <-> intermediate format <-> whatever version"  tool, so you can get items without loss across versions. But that is easier said than done(especially the flattening of materials).
