### ISSUE TITLE
NBTTagList missing?

### ISSUE THREAD

**Issue by ShaneBeee** [tr7zw/Item-NBT-API#98]
Am I crazy or is this plugin missing an NBTTagList class?

You can get the type NBTType#NBTTagList but there is no actual NBTTagList class.

I was trying to get the Motion tag from a player's NBT (just testing all the stuff) and I cant seem to actually get its values.

Thanks for reading!

**Comment by tr7zw** [comment]
The class is called NBTCompoundList(all other lists like Strings just use the Java List<String> interface). To get/create them use for example getCompoundList/getStringList etc (https://github.com/tr7zw/Item-NBT-API/blob/master/item-nbt-api/src/main/java/de/tr7zw/changeme/nbtapi/NBTCompound.java#L665).

**Comment by ShaneBeee** [comment]
Awesome, thanks for letting me know. I'll give it a whirl and try again. I think I tried that but most likely did something wrong.

**Comment by ShaneBeee** [comment]
Ok I worked a little magic and got it all figured out.
Thank you :)
