### ISSUE TITLE
Double printing "[NBTAPI]" to console

### ISSUE THREAD

**Issue by ShaneBeee** [tr7zw/Item-NBT-API#99]
I noticed when using this API, that "[NBTAPI]" is printed twice to console,
ex:
```
[14:28:20 INFO]: [NBTAPI] [NBTAPI] Found Spigot: v1_16_R1! Trying to find NMS support
[14:28:20 INFO]: [NBTAPI] [NBTAPI] NMS support 'MC1_16_R1' loaded!
[14:28:20 INFO]: [NBTAPI] [NBTAPI] Using the plugin 'PermissionsEx' to create a bStats instance!
```

I noticed this was happening due to this:
Getting the logger "NBTAPI"
https://github.com/tr7zw/Item-NBT-API/blob/65a86027baaa292324db921e9208c638fd23f194/item-nbt-api/src/main/java/de/tr7zw/changeme/nbtapi/utils/MinecraftVersion.java#L30

But then also adding "NBTAPI" to logging messages:
https://github.com/tr7zw/Item-NBT-API/blob/65a86027baaa292324db921e9208c638fd23f194/item-nbt-api/src/main/java/de/tr7zw/changeme/nbtapi/utils/MinecraftVersion.java#L69

Maybe an option here could be one of the following:
1) Remove "NBTAPI" from the messages
2) for the logger use `Bukkit.getLogger()`
3) Make the Logger not final, so a plugin implementing this API could change the logger to a logger of their choice.

**Comment by tr7zw** [comment]
I'll remove the legacy prefix from the message. The point of the logger was to use a correct logger and to get rid of the duplicated "[NBTAPI]" everywhere.

**Comment by ShaneBeee** [comment]
No I didn't configure the logger to do anything. 
I literally just use the API for entities/items/block entities.

**Comment by tr7zw** [comment]
Yea but it looks like something changed the configuration of the logger(probably some other plugin), since in for example [here](https://github.com/tr7zw/Item-NBT-API/runs/941333678?check_suite_focus=true#step:4:12111) everything looks fine. May be worth to add a logger configuration to the lib itself to print the prefix and then remove the hard-coded prefix everywhere.

**Comment by ShaneBeee** [comment]
Ok did some testing, turns out its something to do with Paper

### Spigot:
<img width="747" alt="Screen Shot 2020-08-10 at 1 27 34 AM" src="https://user-images.githubusercontent.com/20008482/89764194-d3bd9780-daa8-11ea-9227-08a60ec5afe3.png">

### Paper:
<img width="747" alt="Screen Shot 2020-08-10 at 1 28 23 AM" src="https://user-images.githubusercontent.com/20008482/89764213-d9b37880-daa8-11ea-885d-c16268b8d643.png">

Im guessing Paper prints the name of whatever Logger you chose, ie: getLogger("NBTAPI")

**Comment by tr7zw** [comment]
Good to know that Paper changes the logger that way. I'll add the needed configurations to follow Paper's logging.

**Comment by ShaneBeee** [comment]
I just wanted to re-suggest my earlier suggestion:
> Make the Logger not final, so a plugin implementing this API could change the logger to a logger of their choice.

Currently I am using a fork of the plugin which I changed that field to public, allowing me to change the logger within my own plugin.

This is how it looks:
<img width="534" alt="Screen Shot 2020-10-25 at 3 49 31 PM" src="https://user-images.githubusercontent.com/20008482/97121201-aeb8e800-16d9-11eb-801a-90d051fcedd9.png">

In my opinion it looks a little cleaner and better integrated into the plugin.
A friend of mine just came across this same issue, he is now using my fork as well, so he can customize the prefix in the message.

Making this field public I feel would help out a lot of devs using this API.

**Comment by tr7zw** [comment]
Added the method to replace the logger. Technically doesn't fix the issue with the spigot and paper loggers looking different, but not sure how to tackle that in a good way currently.

**Comment by ShaneBeee** [comment]
Thank you very much, I really appreciate it!
